# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170205_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_type',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
