# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170206_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='audio_type',
            new_name='audio_file',
        ),
    ]
